# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import webbrowser
import os


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(250, 300)
                MainWindow.setMinimumSize(QtCore.QSize(250, 300))
                MainWindow.setMaximumSize(QtCore.QSize(250, 300))
                font = QtGui.QFont()
                font.setFamily("MS Sans Serif")
                MainWindow.setFont(font)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setMinimumSize(QtCore.QSize(250, 300))
                self.centralwidget.setMaximumSize(QtCore.QSize(250, 16777215))
                self.centralwidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
                self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
                self.centralwidget.setObjectName("centralwidget")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setEnabled(True)
                self.label.setGeometry(QtCore.QRect(0, 0, 301, 81))
                font = QtGui.QFont()
                font.setPointSize(40)
                self.label.setFont(font)
                self.label.setStyleSheet("color: rgb(255, 255, 255);")
                self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.label.setObjectName("label")
                self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
                self.openGLWidget.setEnabled(True)
                self.openGLWidget.setGeometry(QtCore.QRect(-10, 0, 300, 400))
                self.openGLWidget.setStatusTip("")
                self.openGLWidget.setObjectName("openGLWidget")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(10, 260, 110, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.pushButton.setFont(font)
                self.pushButton.setObjectName("pushButton")
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(130, 260, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.pushButton_2.setObjectName("pushButton_2")
                self.r = QtWidgets.QPushButton(self.centralwidget)
                self.r.setGeometry(QtCore.QRect(190, 260, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.r.setFont(font)
                self.r.setStyleSheet("background-color: rgb(255, 170, 0);\n"
        "color: rgb(255, 255, 255);")
                self.r.setObjectName("r")
                self.number1 = QtWidgets.QPushButton(self.centralwidget)
                self.number1.setGeometry(QtCore.QRect(10, 220, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number1.setFont(font)
                self.number1.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number1.setObjectName("number1")
                self.number2 = QtWidgets.QPushButton(self.centralwidget)
                self.number2.setGeometry(QtCore.QRect(70, 220, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number2.setFont(font)
                self.number2.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number2.setObjectName("number2")
                self.number3 = QtWidgets.QPushButton(self.centralwidget)
                self.number3.setGeometry(QtCore.QRect(130, 220, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number3.setFont(font)
                self.number3.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number3.setObjectName("number3")
                self.p = QtWidgets.QPushButton(self.centralwidget)
                self.p.setGeometry(QtCore.QRect(190, 220, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.p.setFont(font)
                self.p.setStyleSheet("background-color: rgb(255, 170, 0);\n"
        "color: rgb(255, 255, 255);")
                self.p.setObjectName("p")
                self._ = QtWidgets.QPushButton(self.centralwidget)
                self._.setGeometry(QtCore.QRect(190, 180, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self._.setFont(font)
                self._.setStyleSheet("background-color: rgb(255, 170, 0);\n"
        "color: rgb(255, 255, 255);")
                self._.setObjectName("_")
                self.number4 = QtWidgets.QPushButton(self.centralwidget)
                self.number4.setGeometry(QtCore.QRect(10, 180, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number4.setFont(font)
                self.number4.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number4.setObjectName("number4")
                self.number5 = QtWidgets.QPushButton(self.centralwidget)
                self.number5.setGeometry(QtCore.QRect(70, 180, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number5.setFont(font)
                self.number5.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number5.setObjectName("number5")
                self.number6 = QtWidgets.QPushButton(self.centralwidget)
                self.number6.setGeometry(QtCore.QRect(130, 180, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number6.setFont(font)
                self.number6.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number6.setObjectName("number6")
                self.x = QtWidgets.QPushButton(self.centralwidget)
                self.x.setGeometry(QtCore.QRect(190, 140, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.x.setFont(font)
                self.x.setStyleSheet("background-color: rgb(255, 170, 0);\n"
        "color: rgb(255, 255, 255);")
                self.x.setObjectName("x")
                self.number7 = QtWidgets.QPushButton(self.centralwidget)
                self.number7.setGeometry(QtCore.QRect(10, 140, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number7.setFont(font)
                self.number7.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number7.setObjectName("number7")
                self.number8 = QtWidgets.QPushButton(self.centralwidget)
                self.number8.setGeometry(QtCore.QRect(70, 140, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number8.setFont(font)
                self.number8.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number8.setObjectName("number8")
                self.number9 = QtWidgets.QPushButton(self.centralwidget)
                self.number9.setGeometry(QtCore.QRect(130, 140, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number9.setFont(font)
                self.number9.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number9.setObjectName("number9")
                self.d = QtWidgets.QPushButton(self.centralwidget)
                self.d.setGeometry(QtCore.QRect(190, 100, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.d.setFont(font)
                self.d.setStyleSheet("color: rgb(255, 255, 255);\n"
        "background-color: rgb(255, 170, 0);")
                self.d.setObjectName("d")
                self.c = QtWidgets.QPushButton(self.centralwidget)
                self.c.setGeometry(QtCore.QRect(10, 100, 50, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.c.setFont(font)
                self.c.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                

                self.number0 = QtWidgets.QPushButton(self.centralwidget)
                self.number0.setGeometry(QtCore.QRect(10, 260, 111, 30))
                font = QtGui.QFont()
                font.setPointSize(20)
                self.number0.setFont(font)
                self.number0.setStyleSheet("background-color: rgb(70, 70, 70);\n"
        "color: rgb(255, 255, 255);")
                self.number0.setObjectName("number0")
                self.openGLWidget.raise_()
                self.label.raise_()
                self.pushButton.raise_()
                self.pushButton_2.raise_()
                self.r.raise_()
                self.number1.raise_()
                self.number2.raise_()
                self.number3.raise_()
                self.p.raise_()
                self._.raise_()
                self.number4.raise_()
                self.number5.raise_()
                self.number6.raise_()
                self.x.raise_()
                self.number7.raise_()
                self.number8.raise_()
                self.number9.raise_()
                self.d.raise_()
                self.c.raise_()
                
                self.number0.raise_()
                MainWindow.setCentralWidget(self.centralwidget)

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)

                self.add_functions()
                self.is_equal = False


        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "Клькулятор"))
                self.label.setText(_translate("MainWindow", "0"))
                self.pushButton.setText(_translate("MainWindow", "0"))
                self.pushButton_2.setText(_translate("MainWindow", ","))
                self.r.setText(_translate("MainWindow", "="))
                self.number1.setText(_translate("MainWindow", "1"))
                self.number2.setText(_translate("MainWindow", "2"))
                self.number3.setText(_translate("MainWindow", "3"))
                self.p.setText(_translate("MainWindow", "+"))
                self._.setText(_translate("MainWindow", "-"))
                self.number4.setText(_translate("MainWindow", "4"))
                self.number5.setText(_translate("MainWindow", "5"))
                self.number6.setText(_translate("MainWindow", "6"))
                self.x.setText(_translate("MainWindow", "x"))
                self.number7.setText(_translate("MainWindow", "7"))
                self.number8.setText(_translate("MainWindow", "8"))
                self.number9.setText(_translate("MainWindow", "9"))
                self.d.setText(_translate("MainWindow", "/"))
                self.c.setText(_translate("MainWindow", "c"))
                
                self.number0.setText(_translate("MainWindow", "0"))
                #self.label.setText("")

        def add_functions(self):
                self.number0.clicked.connect(lambda: self.write_number(self.number0.text()))
                self.number1.clicked.connect(lambda: self.write_number(self.number1.text()))
                self.number2.clicked.connect(lambda: self.write_number(self.number2.text()))
                self.number3.clicked.connect(lambda: self.write_number(self.number3.text()))
                self.number4.clicked.connect(lambda: self.write_number(self.number4.text()))
                self.number5.clicked.connect(lambda: self.write_number(self.number5.text()))
                self.number6.clicked.connect(lambda: self.write_number(self.number6.text()))
                self.number7.clicked.connect(lambda: self.write_number(self.number7.text()))
                self.number8.clicked.connect(lambda: self.write_number(self.number8.text()))
                self.number9.clicked.connect(lambda: self.write_number(self.number9.text()))
                self.x.clicked.connect(lambda: self.write_number("*"))
                self.p.clicked.connect(lambda: self.write_number(self.p.text()))
                self._.clicked.connect(lambda: self.write_number(self._.text()))
                self.d.clicked.connect(lambda: self.write_number(self.d.text()))
                self.c.clicked.connect(lambda: self.write_number(self.c.text()))
                self.pushButton_2.clicked.connect(lambda: self.write_number("."))
                

                self.r.clicked.connect(self.results)
                

        


        

                



        def write_number(self, number):
                print(number)
                tt = self.label.text()
                if tt == '0' or self.is_equal:
                        self.label.setText('')
                        self.is_equal = False
                
                if number == "c":
                        results = '0'
                
                else:

                        results = self.label.text() + number
                
                
                self.label.setText(results)

        def results(self):
                if not self.is_equal:
                        font = QtGui.QFont()
                        font.setFamily("MS Sans Serif")
                        res = eval(self.label.text())
                        font.setPointSize(14)
                        self.label.setFont(font)
                        self.label.setText("Результат: " + str(res))
                         
                        self.is_equal = True
                else:
                        
                        error = QMessageBox()
                        error.setWindowTitle("Второе ровно!")
                        error.setText("Вы уже получили результат!")
                        error.setIcon(QMessageBox.Information)
                        error.setStandardButtons(QMessageBox.Ok)                
                        error.setInformativeText("Проверка на дурака пройдена!")
                        
                        
                        error.exec_()


        
                        

                                



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
